### ISSUE TITLE
[NB-System-Properties] Update the plugin for NetBeans 8.2 needed

### ISSUE THREAD

**Issue by Git-GT** [manikantannaren/mynetbeans#10]
Hi, 
could you kindly update this plugin to let it work also with Netbeans 8.2?
Considering that there are not many core differences with Netbeans 8.0 I guess it will be sufficient to simply update the plugin file descriptor and publish it on the repo.
Thanks and best regards

**Comment by m-sivasubramanyan** [comment]
Are you referring to the Create archive plugin?

**Comment by Git-GT** [comment]
Sorry I didn't noticed that this issue tracker was for all your plugins.
I was referring to system properties plugin. 
Thanks,

PS: I have also a suggestion for a new feature it would be great if it was also able to set the windows environment variables like path, classpath etc.

**Comment by m-sivasubramanyan** [comment]
Can you create a enhancement request for that please. Marking the issue as [NB-System-Properties]. Thank you. I will work on updating the plugin.

**Comment by manikantannaren** [comment]
The plugin works for 8.2. Did you face any issue during upgrade?
The environment variables are available under the Environment variables node.

**Comment by Git-GT** [comment]
I just installed the new version of the plugin. 
Netbeans signaled me an exception after installation but I' m not sure if it is related to the plugin itself or to something else. 
For now the plugin works and it is great, if I will see some error I will open a issue report.
Thanks a lot for updating it!
Best regards
