### ISSUE TITLE
[NB-System-Properties] Show the system variables that contains multiple values separated by ";" as a tree

### ISSUE THREAD

**Issue by Git-GT** [manikantannaren/mynetbeans#11]
Hi, 
it would be nice if the system variables containing multiple values separated by ";" were showed like a tree.

For example:
PATH = C:\ProgramData\Oracle\Java\javapath;C:\Program Files\IBM\RationalSDLC\common;D:\Java\jdk1.7.0_85\bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem

will always be shown in a single line but with the addition of a small "+" on the left that allows to expand it as 
PATH : <Full path string>
    | ------   C:\ProgramData\Oracle\Java\javapath
    | ------   C:\Program Files\IBM\RationalSDLC\common
    | ------   D:\Java\jdk1.7.0_85\bin
    | ------   C:\windows\system32
    | ------   C:\windows;C:\windows\System32\Wbem

**Comment by manikantannaren** [comment]
Implemented as a Custom editor, The separated entries are shown on clicking the "..." button beside the property value.

**Comment by manikantannaren** [comment]
Commit 7e573f33e57582c5347640f5327b22d1e25165e8

**Comment by manikantannaren** [comment]
@Gittino, can you please verify using latest changes before I Update the plugin on plugin portal

**Comment by Git-GT** [comment]
Yes, it seems to work, you can update it in the netbeans plugin repository! 
Thanks a lot!
Best,
