### ISSUE TITLE
[NB-CapsLock-Notifier] - Readable problem with Darcula Theme

### ISSUE THREAD

**Issue by Chris2011** [manikantannaren/mynetbeans#15]
I tested your plugin and I use darcula and the word CAPS is not readable in the statusbar:

![capslockdarcula](https://cloud.githubusercontent.com/assets/795658/21228783/66c93722-c2df-11e6-97bd-6fcc4439a3f7.png)

**Comment by manikantannaren** [comment]
Fixed. Picks foreground and back ground from L&F defaults.

**Comment by Chris2011** [comment]
Thx, Will test after a new release :)
