### ISSUE TITLE
[NB-CapsLock-Notifier] - Please use the notifier API

### ISSUE THREAD

**Issue by Chris2011** [manikantannaren/mynetbeans#16]
The plugin is nice, but the word CAPS will not really capturing your attention, so it would be better, to use the notifier, because its called NB-CapsLock-Notifier, so it should interact like this. If you use the official notify API, it will capture your attention better than such a little word. Maybe it could be customized, that some can use real notifier and others can use the default behaviour.

Regards

Chris

**Comment by manikantannaren** [comment]
By Official Notifier API, I am assuming the "balloon" notification. That would be a good idea plus I would learn another API. Thanks for the suggestion.

**Comment by Chris2011** [comment]
yes the ballon notifications :)

**Comment by manikantannaren** [comment]
Fixed as

**Comment by manikantannaren** [comment]
Ballon implemented but notification is dispatched twice when the CAPS key is pressed to On state.

**Comment by manikantannaren** [comment]
So keeping it open.

**Comment by Chris2011** [comment]
Thx, will test it after a new release :)

**Comment by manikantannaren** [comment]
Fixed
1. Check if notification is showing or not before showing balloon
2. Used NB api ImageUtilities to load image icon instead of ImageIO

**Comment by Chris2011** [comment]
Can you make a release with an NBM file please?

**Comment by manikantannaren** [comment]
Oops! Available now.

I built plugin but forget to complete last step - upload to plugin portal.

**Comment by Chris2011** [comment]
Tested and worked, thx.
