### ISSUE TITLE
[NB-System-Properties] - Add the props as a new node to the services window

### ISSUE THREAD

**Issue by Chris2011** [manikantannaren/mynetbeans#20]
I think it could be better to add those nodes as sub nodes to a root node inside the services tab like ->
- System Properties
   - Enviroment variables
   - JVM properties
   - NetBeans properties

Only a suggestion to prevent a lot of windows for everything.

Regards

Chris

**Comment by manikantannaren** [comment]
The services node is too constricted in view real-estate.
I kept the window in the editor because of sheer volume of properties.
