### ISSUE TITLE
[NB-Create-Archive] Move action from run to tools

### ISSUE THREAD

**Issue by Chris2011** [manikantannaren/mynetbeans#24]
Maybe you had an intention for that but IMHO it should be inside Menu/BuildProject: https://github.com/manikantannaren/mynetbeans/blob/0fc89c8bd49d529b7bb3f85b170094f1dcf1f158/NB-Create-Archive/src/org/pr/nb/zip/ArchiverAction.java#L48

So I think you should move the action from Run to Tools. That makes much more sense.

**Comment by Chris2011** [comment]
If you agree with that, I can provide a PR.

**Comment by manikantannaren** [comment]
I think it will be better to move it to File menu instead since the Tools menu refer to IDE toolset. The File menu already has options to Import and export projects.

**Comment by Chris2011** [comment]
Hm yeah, could be good there.

**Comment by Chris2011** [comment]
@manikantannaren Please have a look into the PR. Thx :)

**Comment by Chris2011** [comment]
Sry for that, I changed the line endings, Now it is correct.
