### ISSUE TITLE
[NB-Create-Archive] - Can't install plugin, favorites is needed.

### ISSUE THREAD

**Issue by Chris2011** [manikantannaren/mynetbeans#3]
I use Windows 7 and Netbeans 8.0.2. I downloaded the plugin and when I wanted to install it, I got this message: 
![exporttoarchive](https://cloud.githubusercontent.com/assets/795658/8545791/52a364a6-24b2-11e5-9f6c-aae22ce1be32.png)

Which plugin is this? I didn't find it. Only View files in Favorites. But didn't test it yet.

**Comment by manikantannaren** [comment]
The favorites module is an IDE module, it does not have public APIs yet and I had to rely on Implementation version rather than the spec version. I will upload soon a newer version removing the dependency on Favorites module.

**Comment by manikantannaren** [comment]
Removed the impeding references.

**Comment by Chris2011** [comment]
It works, thx.
