### ISSUE TITLE
[NB-Create-Archive] - Please add a context menu entry and a shortcut

### ISSUE THREAD

**Issue by Chris2011** [manikantannaren/mynetbeans#5]
The plugin works very well with the toolbar button, but for me as a strong keyboard user, I would like to have a context menu entry and for example a shortcut. So I can type Ctrl + 3 (Favorite window), hit the context menu key, select "Extract to archive" or whatever or to hit ctrl + shift+alt+whatever to do the action.

Regards

Chris

**Comment by manikantannaren** [comment]
he nearest unclaimed one hand keyboard  key combination I found is Ctrl+Shift+F3 (Cmd+Shift+F3 on Mac). Going with that.

**Comment by Chris2011** [comment]
Works very nice, only the context menu is missing now.

**Comment by manikantannaren** [comment]
The context menu is a troublesome player. 
Folders - Ok
Project node -OK
Source Packages Node - NOT OK. But can select the src node in Files view
File types - NOT OK Have to go on registering per mime type. Is there a better way? _Still looking_

I think I will keep the issue in open state till a confirmation is available for the NOT OK items

**Comment by Chris2011** [comment]
So I would really like to see the context menu for folders and project nodes. I know there is the option to Export project -> to zip... but this menu is unconfortable. I have to select a project and go to file -> export project -> to zip. I would like to use your plugin to folders (I tested to create a plugin for folder context menu too and this is very simple) and for projects. For files and Source packages, you can develop it later. If you need help, ask me :)

**Comment by manikantannaren** [comment]
For folders, it is as simple as registering action for Loaders/folder/any
Source package node, webpage nodes etc, requires some further research.

I am currently AFK for another 10 days and will be unable to push these changes. 
if it is ok with you, I can add you as a collaborator to the repo

**Comment by Chris2011** [comment]
Sure, do it :).

**Comment by Chris2011** [comment]
Here you can see the add for the Projects and Folders: 810a5ba7d1edda702f084632ff4583da9b7c246d

**Comment by Chris2011** [comment]
tested (Without unit tests). It works like expected.

**Comment by Chris2011** [comment]
I think this is what we are looking for, isn't it? https://github.com/hajdam/deltahex-netbeans/blob/master/src/org/exbin/deltahex/netbeans/Installer.java

**Comment by manikantannaren** [comment]
Wow! nice find. I will try implementing it. Will be a couple of days though before I can commit changes.

**Comment by Chris2011** [comment]
Sounds great. :)

**Comment by manikantannaren** [comment]
@Chris2011 I have merged the changes. Can you please get latest from master and check - before I publish the NBM? Thank you in advance and double thank your for finding a solution.

**Comment by manikantannaren** [comment]
That leaves the nodes like Source Packages, site root etc.

**Comment by Chris2011** [comment]
Thx, i will check it :)

**Comment by Chris2011** [comment]
Tested it and it works like expected :). Thx.

**Comment by Chris2011** [comment]
I think we can close this, it works everything fine :)
